version: '3.8'

services:
  jsmarket:
    container_name: jsmarket-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4200:4200"  # Frontend
      - "3333:3333"  # API
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:///app/data/db.sqlite
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - sqlite_data:/app/data
    networks:
      - jsmarket-prod
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3333/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  jsmarket-prod:
    driver: bridge

volumes:
  sqlite_data:
    name: jsmarket-prod-sqlite
